/**
 * Init — generate config from setup wizard answers.
 *
 * The interactive prompting is done in the CLI layer. This module
 * handles config generation and writing.
 */

import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

export interface InitAnswers {
  developer: string;
  agents: {
    claude_code: boolean;
    codex: boolean;
    cursor: boolean;
  };
  includeOrgs: string[];
  endpoint: string | null;
  apiKey: string | null;
  enableDaemon: boolean;
}

/**
 * Generate a YAML config string from init answers.
 */
export function generateConfig(answers: InitAnswers): string {
  const orgsYaml = answers.includeOrgs.length > 0
    ? answers.includeOrgs.map((o) => `    - ${o}`).join("\n")
    : "    # none configured — run 'observer init' to add corporate orgs";

  const shipEnabled = answers.endpoint !== null;

  return `# Observer agent configuration
# Generated by 'observer init'

developer: ${answers.developer}

sources:
  claude_code: ${answers.agents.claude_code}
  codex: ${answers.agents.codex}
  cursor: ${answers.agents.cursor}

scope:
  include_orgs:
${orgsYaml}

ship:
  enabled: ${shipEnabled}
  endpoint: ${answers.endpoint ?? "null"}
${answers.apiKey ? `  api_key: ${answers.apiKey}` : "  # api_key: null (using Ed25519 signing)"}
  redact_secrets: true

privacy:
  strip_secrets: true
  capture_file_contents: false

daemon:
  enabled: ${answers.enableDaemon}
  poll_interval_ms: 300000  # 5 minutes
`;
}

/**
 * Write config to the state directory.
 * Does not overwrite unless force=true.
 */
export function writeConfig(
  stateDir: string,
  content: string,
  force = false,
): void {
  mkdirSync(stateDir, { recursive: true });
  const configPath = join(stateDir, "config.yaml");

  if (existsSync(configPath) && !force) {
    return;
  }

  writeFileSync(configPath, content);
}
