/**
 * Init — generate config from setup wizard answers.
 *
 * The interactive prompting is done in the CLI layer. This module
 * handles config generation and writing.
 *
 * The YAML keys here MUST match what `loadConfig` reads in config.ts.
 * loadConfig uses camelCase (`redactSecrets`, `localOutputDir`,
 * `pollIntervalMs`, etc.) and a flat `pollIntervalMs` rather than
 * `daemon.poll_interval_ms`. Earlier versions of this file wrote
 * snake_case keys that loadConfig silently ignored — answers vanished
 * on the first daemon poll.
 */

import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

export type DisclosureChoice = "basic" | "moderate" | "sensitive" | "full";

export interface InitAnswers {
  developer: string;
  agents: {
    claude_code: boolean;
    codex: boolean;
    cursor: boolean;
  };
  includeOrgs: string[];
  endpoint: string | null;
  apiKey: string | null;
  enableDaemon: boolean;
  disclosure: DisclosureChoice;
  /** Where the disk-shipper writes normalized JSONL. Defaults to
   *  ~/.observer/traces/normalized so the dashboard finds data. */
  localOutputDir?: string | null;
}

/**
 * Generate a YAML config string from init answers.
 * Keys are camelCase to match the loadConfig schema.
 *
 * Two destinations are emitted by default: a `local-dashboard` disk
 * destination at `~/.observer/traces/normalized` (full disclosure) so the
 * dashboard works out of the box, and a `remote` http destination if the
 * user gave one. Each destination is independent — disclosure, schedule,
 * scope, and redact settings can differ.
 */
export function generateConfig(answers: InitAnswers): string {
  const localOutputDir = answers.localOutputDir
    ?? join(homedir(), ".observer", "traces", "normalized");

  // Local destination — drives the dashboard. Always enabled at full
  // disclosure since data never leaves the machine.
  const localBlock = `  - name: local-dashboard
    endpoint: ${localOutputDir}
    disclosure: full
    schedule: realtime
    useLocalTime: true
    redactSecrets: true`;

  // Remote destination — only when the user specified an ingestor URL.
  // Disclosure follows the wizard's choice. Disk-only data can stay
  // "full" without leaking; HTTP egress should generally be at most
  // "sensitive" (no HIGH_RISK fields).
  const remoteBlock = answers.endpoint
    ? `  - name: remote
    endpoint: ${answers.endpoint}
${answers.apiKey ? `    apiKey: ${answers.apiKey}` : "    # apiKey: null (using Ed25519 signing)"}
    disclosure: ${answers.disclosure === "full" ? "sensitive" : answers.disclosure}
    schedule: hourly
    useLocalTime: false
    redactSecrets: true${answers.includeOrgs.length > 0 ? `
    orgs:
      include:
${answers.includeOrgs.map((o) => `        - ${o}`).join("\n")}` : ""}`
    : "";

  const destinationsBlock = remoteBlock
    ? `${localBlock}\n${remoteBlock}`
    : localBlock;

  return `# Observer agent configuration
# Generated by 'observer init'.
# Keys are camelCase to match the loader.

developer: ${answers.developer}

sources:
  claude_code: ${answers.agents.claude_code}
  codex: ${answers.agents.codex}
  cursor: ${answers.agents.cursor}

# Each destination has its own disclosure, schedule, scope, and redact
# settings. The disk destination drives the local dashboard; the http
# destination ships to a centralized ingestor.
destinations:
${destinationsBlock}

git:
  enabled: true
  repos: {}
  # Only collect commits authored by ${answers.developer}. Set to false
  # if you want teammates' commits in shared repos to show up too.
  onlySelf: true

privacy:
  # Hard exclusion list applied before any destination filter — a path
  # listed here never reaches any destination, regardless of per-dest
  # scope settings.
  excludeProjects: []

cursor:
  # Cursor doesn't write consumed-token counts to its local SQLite —
  # they only live on Cursor's servers. Set to true and the daemon will
  # read your local Cursor auth token (state.vscdb) and call Cursor's
  # dashboard API once per tick to fetch real per-day totals.
  # Tradeoff: that token is account-equivalent. Off by default.
  fetchUsage: false

# Daemon poll interval in milliseconds. 300000 = 5 minutes.
pollIntervalMs: 300000

# Dashboard server config (used by 'observer dashboard run').
dashboard:
  port: 3457
  uiPort: 3000
  dataDir: null            # null → ~/.observer/traces/normalized
  log:
    level: info            # silent | error | info | debug
    file: null             # null → ~/.observer/logs/dashboard.log
    stderr: false
`;
}

/**
 * Write config to the state directory.
 * Does not overwrite unless force=true.
 */
export function writeConfig(
  stateDir: string,
  content: string,
  force = false,
): void {
  mkdirSync(stateDir, { recursive: true });
  const configPath = join(stateDir, "config.yaml");

  if (existsSync(configPath) && !force) {
    return;
  }

  writeFileSync(configPath, content);
}
