/**
 * Init — generate config from setup wizard answers.
 *
 * The interactive prompting is done in the CLI layer. This module
 * handles config generation and writing.
 *
 * The YAML keys here MUST match what `loadConfig` reads in config.ts.
 * loadConfig uses camelCase (`redactSecrets`, `localOutputDir`,
 * `pollIntervalMs`, etc.) and a flat `pollIntervalMs` rather than
 * `daemon.poll_interval_ms`. Earlier versions of this file wrote
 * snake_case keys that loadConfig silently ignored — answers vanished
 * on the first daemon poll.
 */

import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

export type DisclosureChoice = "basic" | "moderate" | "sensitive" | "full";

export interface InitAnswers {
  developer: string;
  agents: {
    claude_code: boolean;
    codex: boolean;
    cursor: boolean;
  };
  includeOrgs: string[];
  endpoint: string | null;
  apiKey: string | null;
  enableDaemon: boolean;
  disclosure: DisclosureChoice;
  /** Where the disk-shipper writes normalized JSONL. Defaults to
   *  ~/.observer/traces/normalized so the dashboard finds data. */
  localOutputDir?: string | null;
}

/**
 * Generate a YAML config string from init answers.
 * Keys are camelCase to match the loadConfig schema.
 */
export function generateConfig(answers: InitAnswers): string {
  const localOutputDir = answers.localOutputDir
    ?? join(homedir(), ".observer", "traces", "normalized");

  const excludeProjectsYaml = "    # add project names to exclude from collection";

  return `# Observer agent configuration
# Generated by 'observer init'.
# Keys are camelCase to match the loader.

developer: ${answers.developer}

sources:
  claude_code: ${answers.agents.claude_code}
  codex: ${answers.agents.codex}
  cursor: ${answers.agents.cursor}

ship:
  # Remote ingestor endpoint, or null for local-only.
  endpoint: ${answers.endpoint ?? "null"}
${answers.apiKey ? `  apiKey: ${answers.apiKey}` : "  # apiKey: null (using Ed25519 signing)"}
  # Disk-shipper output dir — where normalized JSONL is written. The
  # dashboard reads from here. Set to null to disable disk shipping.
  localOutputDir: ${localOutputDir}
  redactSecrets: true
  # Data capture level. "full" keeps tool outputs and file contents —
  # only safe when endpoint is null (local-only).
  disclosure: ${answers.disclosure}
  schedule: hourly
  useLocalTime: false
  anonymize: false

git:
  enabled: true
  repos: {}

privacy:
  excludeProjects: []
${excludeProjectsYaml}

# Daemon poll interval in milliseconds. 300000 = 5 minutes.
pollIntervalMs: 300000

# Dashboard server config (used by 'observer dashboard run').
dashboard:
  port: 3457
  uiPort: 3000
  dataDir: null            # null → ~/.observer/traces/normalized
  log:
    level: info            # silent | error | info | debug
    file: null             # null → ~/.observer/logs/dashboard.log
    stderr: false
`;
}

/**
 * Write config to the state directory.
 * Does not overwrite unless force=true.
 */
export function writeConfig(
  stateDir: string,
  content: string,
  force = false,
): void {
  mkdirSync(stateDir, { recursive: true });
  const configPath = join(stateDir, "config.yaml");

  if (existsSync(configPath) && !force) {
    return;
  }

  writeFileSync(configPath, content);
}
