import { defineConfig, devices } from "@playwright/test";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DATA_DIR = resolve(__dirname, "tests/e2e/fixtures/data");

// Dedicated test port — distinct from the dashboard's default 3457 so
// a developer's local `observer dashboard run` (which also listens on
// 3457) can't be reused by Playwright. With `reuseExistingServer: true`
// we'd silently bind to that running server, which serves real
// `~/.observer/traces/normalized` data instead of the seeded fixture
// — every fixture-scoped assertion ("project: alpha", "5 findings",
// etc.) then fails non-deterministically based on whatever the user
// happens to have collected.
const TEST_PORT = 3458;
const TEST_URL = `http://localhost:${TEST_PORT}`;

/**
 * Playwright e2e for the dashboard. The server reads its data dir from
 * OBSERVER_DATA_DIR; we point it at a generated fixture so the tests don't
 * depend on whatever the user happens to have in ~/.observer.
 *
 * The fixture is generated by `tests/e2e/seed.ts`, which the `test:e2e`
 * npm script runs BEFORE `playwright test`. It used to be a globalSetup,
 * but the server scans OBSERVER_DATA_DIR once at boot and Playwright
 * starts webServer in parallel with globalSetup — so the cached snapshot
 * was always empty. Pre-seeding via the npm script avoids the race.
 */
export default defineConfig({
  testDir: "./tests/e2e",
  fullyParallel: false,           // single Bun server process
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: process.env.CI ? "github" : "list",

  use: {
    baseURL: TEST_URL,
    trace: "on-first-retry",
    screenshot: "only-on-failure",
  },

  projects: [
    { name: "chromium", use: devices["Desktop Chrome"] },
  ],

  webServer: {
    // CI builds the dashboard in a prior workflow step, so the webServer
    // doesn't need to rebuild here. We just start the Bun server and
    // point it at the seeded fixture. (Local devs are expected to have
    // run `bun run build` once; the dev-loop optimisation isn't worth
    // the doubled startup time on every test run.)
    command: "bun server/index.ts",
    url: TEST_URL,
    // NEVER reuse — even locally. The previous default
    // (`!process.env.CI`) silently rebound to a developer's running
    // dashboard on 3457, which serves real data and breaks fixture
    // assertions in non-obvious ways. The dedicated TEST_PORT means
    // there's no risk of contention either.
    reuseExistingServer: false,
    timeout: 60_000,
    // Use the resolved absolute path so the data dir is unambiguous —
    // earlier we relied on shell `$PWD`, which depends on whatever
    // cwd Playwright spawns the subprocess in. The spread of process.env
    // is critical: Playwright's `env:` REPLACES the child env rather
    // than merging, so without this PATH/HOME/etc. are missing and the
    // bun process may misbehave (silently empty fixture in CI was
    // traced to this).
    env: {
      ...(process.env as Record<string, string>),
      OBSERVER_PORT: String(TEST_PORT),
      OBSERVER_DATA_DIR: FIXTURE_DATA_DIR,
      // Bypass the dashboard's foreign-commit filter for tests — the
      // fixture authors don't match the developer's real config.yaml,
      // so without this every fixture commit gets dropped at ingest.
      OBSERVER_SKIP_FOREIGN_FILTER: "1",
    },
  },
});
