import { defineConfig, devices } from "@playwright/test";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DATA_DIR = resolve(__dirname, "tests/e2e/fixtures/data");

/**
 * Playwright e2e for the dashboard. The server reads its data dir from
 * OBSERVER_DATA_DIR; we point it at a generated fixture so the tests don't
 * depend on whatever the user happens to have in ~/.observer.
 *
 * The fixture is generated by `tests/e2e/seed.ts` before the suite via the
 * globalSetup hook below. The Bun static export must already be built —
 * `bun run build` is wired in as part of `webServer.command`.
 */
export default defineConfig({
  testDir: "./tests/e2e",
  fullyParallel: false,           // single Bun server process
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: process.env.CI ? "github" : "list",
  globalSetup: "./tests/e2e/seed.ts",

  use: {
    baseURL: "http://localhost:3457",
    trace: "on-first-retry",
    screenshot: "only-on-failure",
  },

  projects: [
    { name: "chromium", use: devices["Desktop Chrome"] },
  ],

  webServer: {
    // Skip rebuild between test runs in dev — assume the developer ran
    // `bun run build` once. CI wires its own build step before tests.
    command: process.env.CI
      ? "bun run build && OBSERVER_DATA_DIR=$PWD/tests/e2e/fixtures/data OBSERVER_SKIP_FOREIGN_FILTER=1 bun server/index.ts"
      : "OBSERVER_DATA_DIR=$PWD/tests/e2e/fixtures/data OBSERVER_SKIP_FOREIGN_FILTER=1 bun server/index.ts",
    url: "http://localhost:3457",
    reuseExistingServer: !process.env.CI,
    timeout: 60_000,
    env: {
      OBSERVER_DATA_DIR: FIXTURE_DATA_DIR,
      // Bypass the dashboard's foreign-commit filter for tests — the
      // fixture authors don't match the developer's real config.yaml,
      // so without this every fixture commit gets dropped at ingest.
      OBSERVER_SKIP_FOREIGN_FILTER: "1",
    },
  },
});
