/**
 * Merge an existing Claude Code `permissions.allow` list with a fresh
 * candidate list generated by Observer. Pure function — no DOM, no
 * fetches; trivially unit-testable.
 *
 * Two main rules:
 *
 *   1. Union: every entry in either list ends up in the merge unless
 *      step 2 removes it. We never drop a user-curated entry just
 *      because Observer didn't witness its use.
 *
 *   2. Subsumption: an entry is removed when another entry strictly
 *      covers it. Specifically — for Bash entries — a verb-level
 *      wildcard (`Bash(bun:*)` or `Bash(bun *)`) subsumes any longer
 *      Bash entry that begins with the same verb (`Bash(bun install *)`,
 *      `Bash(bun --version)`, `Bash(bun install foo)`).
 *
 * Entries Observer can't reason about (e.g. `WebFetch(domain:github.com)`,
 * exact `Bash(curl -sL "...")` strings) are passed through unchanged. We
 * only merge inside the Bash family and exact-name tools we recognise.
 */

export interface AllowEntry {
  /** Original verbatim string — what we emit back to the user. */
  raw: string;
  /** Tool family — "Bash", "Read", "WebFetch", "mcp:db-mcp:shell", etc. */
  tool: string;
  /** Tokens after the tool name, with trailing `*` markers normalised
   *  to the literal `*`. Empty for tool-only entries like `"Read"`. */
  tokens: string[];
  /** True if the entry ends with a wildcard (covers anything below). */
  wildcard: boolean;
  /** True if Observer can apply subsumption rules to this entry shape.
   *  For non-Bash + non-tool-only entries we leave the raw string alone. */
  reasonable: boolean;
}

export interface MergeResult {
  /** Final list, deduplicated, sorted lexicographically. */
  merged: string[];
  /** Entries that were in the candidate but not the existing list. */
  added: string[];
  /** Entries removed from the existing list because something else subsumes them. */
  subsumed: Array<{ entry: string; subsumedBy: string }>;
}

/**
 * Parse an allowlist entry into a structured form. Returns null if we
 * can't parse it; callers should treat unparsed entries as opaque
 * pass-throughs.
 */
export function parseAllowEntry(raw: string): AllowEntry | null {
  raw = raw.trim();
  if (!raw) return null;

  const parenIdx = raw.indexOf("(");
  if (parenIdx === -1) {
    // Tool-only entry like "Read", "WebSearch", "mcp__db__shell".
    return { raw, tool: raw, tokens: [], wildcard: false, reasonable: true };
  }
  if (!raw.endsWith(")")) return null;

  const tool = raw.slice(0, parenIdx);
  const inner = raw.slice(parenIdx + 1, -1).trim();
  if (!inner) return { raw, tool, tokens: [], wildcard: false, reasonable: true };

  // Bash uses two equivalent suffix forms for "anything follows":
  //   Bash(verb:*)   — Anthropic's docs / Claude Code
  //   Bash(verb *)   — older form, still accepted in many configs
  // Observer emits :* form; users frequently have the space form.
  // For everything else (e.g. WebFetch(domain:...)), the colon is
  // semantic, not a wildcard — leave alone.
  if (tool === "Bash" || tool === "Shell") {
    let body = inner;
    let wildcard = false;
    if (body.endsWith(":*")) { body = body.slice(0, -2).trim(); wildcard = true; }
    else if (body.endsWith(" *")) { body = body.slice(0, -2).trim(); wildcard = true; }
    const tokens = body.length > 0 ? body.split(/\s+/) : [];
    return { raw, tool, tokens, wildcard, reasonable: true };
  }

  // Other tools (WebFetch(domain:x), mcp:server:tool(arg), etc.) —
  // we don't model arg semantics, so subsumption is exact-string only.
  return { raw, tool, tokens: [inner], wildcard: false, reasonable: false };
}

/**
 * Does `a` subsume `b`? An entry subsumes another when it is at least
 * as permissive — observing `b` would be allowed by `a`, but not vice
 * versa.
 *
 *  Bash(bun:*)        subsumes  Bash(bun install *)
 *  Bash(bun install *) subsumes Bash(bun install foo)
 *  Bash(bun:*)        does NOT subsume Bash(npm:*)         (different verb)
 *  Bash(bun install)  does NOT subsume Bash(bun install *) (no wildcard)
 *
 * For non-reasonable entries: they only subsume themselves
 * (string-equality dedup).
 */
export function subsumes(a: AllowEntry, b: AllowEntry): boolean {
  if (a.tool !== b.tool) return false;
  if (a.raw === b.raw) return true;
  if (!a.reasonable || !b.reasonable) return false;
  // a must be a wildcard entry to subsume anything beyond exact-equal.
  if (!a.wildcard) return false;
  // a's tokens must be a prefix of b's tokens.
  if (a.tokens.length > b.tokens.length) return false;
  for (let i = 0; i < a.tokens.length; i++) {
    if (a.tokens[i] !== b.tokens[i]) return false;
  }
  return true;
}

/**
 * Merge two allow lists. The result is deduplicated by subsumption and
 * sorted lexicographically. The caller gets the merged list plus a diff
 * (what was added, what was subsumed) so they can review the change.
 */
export function mergeAllowlists(existing: string[], candidate: string[]): MergeResult {
  const all: AllowEntry[] = [];
  const seen = new Set<string>();
  const fromCandidate = new Set<string>();
  for (const raw of existing) {
    const parsed = parseAllowEntry(raw);
    if (!parsed) continue;
    if (seen.has(parsed.raw)) continue;
    seen.add(parsed.raw);
    all.push(parsed);
  }
  for (const raw of candidate) {
    const parsed = parseAllowEntry(raw);
    if (!parsed) continue;
    if (seen.has(parsed.raw)) continue;
    seen.add(parsed.raw);
    all.push(parsed);
    fromCandidate.add(parsed.raw);
  }

  // Drop any entry that another entry strictly subsumes.
  const subsumed: Array<{ entry: string; subsumedBy: string }> = [];
  const kept: AllowEntry[] = [];
  for (const a of all) {
    let by: AllowEntry | null = null;
    for (const b of all) {
      if (a === b) continue;
      if (subsumes(b, a) && !subsumes(a, b)) { by = b; break; }
    }
    if (by) {
      subsumed.push({ entry: a.raw, subsumedBy: by.raw });
    } else {
      kept.push(a);
    }
  }

  const existingSet = new Set(existing.map((s) => s.trim()).filter(Boolean));
  const merged = kept.map((e) => e.raw).sort();
  const added = merged.filter((m) => fromCandidate.has(m) && !existingSet.has(m));

  return { merged, added, subsumed };
}
